name: publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node 8
        uses: actions/setup-node@v1
        with:
          node-version: 8
          registry-url: 'https://registry.npmjs.org'
      - name: Install package dependencies
        run: yarn install --frozen-lockfile
      - name: Build project
        run: yarn run build
      - name: Publish to npm
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}